name: sweyer
description: Open source music player built with Flutter
homepage: https://github.com/nt4f04uNd/sweyer
repository: https://github.com/nt4f04uNd/sweyer
issue_tracker: https://github.com/nt4f04uNd/sweyer/issues
publish_to: none
version: 1.0.2+3
 
environment:
  sdk: ">=2.6.0<3.0.0"
  # flutter: 2.1.0-13.0.pre.574 # commit https://github.com/flutter/flutter/commit/02efffc

dependencies:
  # color_thief_flutter: ^1.0.2
  async: ^2.5.0
  rxdart: ^0.26.0
  sliver_tools: ^0.2.1
  animations: ^2.0.0
  permission_handler: ^6.1.1
  shared_preferences: ^2.0.5
  path_provider: ^2.0.1
  percent_indicator: ^3.0.1
  firebase_core: ^1.0.2
  firebase_crashlytics: ^1.0.0
  firebase_analytics: ^7.1.1
  package_info: ^2.0.0
  url_launcher: ^6.0.3
  flare_flutter: ^2.0.6 # TODO: update to 3.0.0 when https://github.com/2d-inc/Flare-Flutter/issues/301 is resolved
  auto_size_text: ^3.0.0-nullsafety.0
  marquee: ^2.0.0
  equatable: ^2.0.0
  device_info: ^2.0.0
  enum_to_string: ^2.0.1
  sqflite: ^2.0.0+2
  path: ^1.7.0
  flutter_sticky_header: ^0.5.0
  multiple_localization: ^0.2.1
  # fluttertoast: ^8.0.3
  fluttertoast:
    # path: C:/dev/projects/native/FlutterToast

    # Using this branch for changing font family
    git: 
      url: https://github.com/nt4f04uNd/fluttertoast/
      ref: f753a91591569acece70a9e8748745efa9faabfb # patch
  # flutter_media_metadata:
  #   path: C:/dev/projects/native/flutter_media_metadata

  #   # git: https://github.com/alexmercerind/flutter_media_metadata
  just_audio:
    ^0.7.3
    # path: C:/dev/projects/native/just_audio/just_audio
    # git: 
    #   url: C:/dev/projects/native/just_audio
    #   ref: master
    #   path: just_audio
  audio_service:
    # Using this branch for custom notifications https://github.com/nt4f04uNd/audio_service/commits/sweyer
    # See https://github.com/ryanheise/audio_service/issues/633
    path: C:/dev/projects/native/audio_service/audio_service

    # NOTE: this is not working for some reason
    # git:
    #   url: https://github.com/nt4f04uNd/audio_service/
    #   ref: c8e99b6b061557ad610f06da2fa706e7205657c0 # sweyer
    #   path: audio_service

    # git: 
    #   url: C:\dev\projects\native\audio_service
    #   ref: one-isolate
    #   path: audio_service
  nt4f04unds_widgets:
    path: c:/dev/projects/native/nt4f04unds_widgets/
    # git:
    #   url: https://github.com/nt4f04uNd/nt4f04unds_widgets/
    #   ref: 1.1.2

dependency_overrides:
  analyzer: ^1.0.0
  petitparser: ^4.0.0
  crypto: ^3.0.0
  audio_session:
    ^0.1.0
    # git: 
    #   url: https://github.com/ryanheise/audio_session.git
    #   ref: master

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  # intl_translation: ^0.17.10+1
  intl_translation:
    git:
      url: https://github.com/nt4f04uNd/intl_translation
      ref: 198ba30710a7aeba94813389dac47c9092d11e6c

flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/images/
    # don't include a whole folder here because of README  
   - assets/animations/play_pause.flr
   - assets/animations/checkmark.flr

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/manrope-extrabold.ttf
          weight: 800
        - asset: assets/fonts/Manrope/manrope-bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope/manrope-semibold.ttf
          weight: 600
