name: sweyer
description: Open source music player built with Flutter
homepage: https://github.com/nt4f04uNd/sweyer
repository: https://github.com/nt4f04uNd/sweyer
issue_tracker: https://github.com/nt4f04uNd/sweyer/issues
publish_to: none
version: 1.0.7+9

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  uuid: ^3.0.4
  path: ^1.8.0
  async: ^2.5.0
  rxdart: ^0.26.0
  sliver_tools: ^0.2.1
  animations: ^2.0.2
  permission_handler: ^8.3.0
  shared_preferences: ^2.0.5
  path_provider: ^2.0.1
  percent_indicator: ^3.0.1
  firebase_core: ^1.0.3
  firebase_crashlytics: ^2.0.1
  firebase_analytics: ^9.0.4
  cloud_functions: ^3.2.4
  package_info_plus: ^1.4.2
  url_launcher: ^6.0.3
  rive: ^0.9.0
  auto_size_text: ^3.0.0-nullsafety.0
  marquee: ^2.1.0
  equatable: ^2.0.0
  device_info_plus: ^3.2.4
  enum_to_string: ^2.0.1
  sqflite: ^2.0.0+3
  boxy: ^2.0.0
  back_button_interceptor: ^5.0.0
  flutter_sticky_header: ^0.6.0
  palette_generator: ^0.3.0
  cached_network_image: ^3.0.0
  flutter_cache_manager: ^3.1.1
  clock: ^1.1.0
  styled_text: ^5.1.0
  android_content_provider: ^0.2.2
  collection: ^1.16.0

  # quick_actions: ^0.6.0 # TODO: quick actions are blocked on https://github.com/ryanheise/audio_service/issues/671

  # fluttertoast: ^8.0.3
  fluttertoast:
    # path: C:/dev/projects/native/FlutterToast

    # Using this branch for changing font family
    git: 
      url: https://github.com/nt4f04uNd/fluttertoast/
      ref: f753a91591569acece70a9e8748745efa9faabfb # patch
  just_audio: ^0.9.18
  
    # path: C:/dev/projects/native/just_audio/just_audio
  
    # git: 
    #   url: C:/dev/projects/native/just_audio
    #   ref: master
    #   path: just_audio
  audio_service:
    # Using this branch for custom notifications https://github.com/nt4f04uNd/audio_service/commits/sweyer
    # See https://github.com/ryanheise/audio_service/issues/633

    # path: C:/dev/projects/native/audio_service/audio_service

    git: 
      url: https://github.com/nt4f04uNd/audio_service
      ref: sweyer
      path: audio_service

    # git: 
    #   url: C:\dev\projects\native\audio_service
    #   ref: one-isolate
    #   path: audio_service
  nt4f04unds_widgets:
    # path: c:/dev/projects/native/nt4f04unds_widgets/

    git:
      url: https://github.com/nt4f04uNd/nt4f04unds_widgets/
      ref: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  golden_toolkit: ^0.13.0

flutter:
  generate: true
  uses-material-design: true

  assets:
   - assets/
   - assets/images/
    # don't include a whole folder here because of README
   - assets/animations/play_pause.riv
   - assets/animations/checkmark.riv

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/manrope-extrabold.ttf
          weight: 800
        - asset: assets/fonts/Manrope/manrope-bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope/manrope-semibold.ttf
          weight: 600
    - family:  SweyerIcons
      fonts:
       - asset: assets/fonts/SweyerIcons/SweyerIcons.ttf
