name: Run Sweyer tests
on:
  pull_request:
  push:
    branches:    
      - main
      - master
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3

      - name: 🧪 Test Sweyer
        uses: ./.github/workflows/test
        with:
          testing_arguments: --coverage

      - name: ☂ Upload Code Coverage
        uses: codecov/codecov-action@v3
