name: Update Goldens
on: 
  workflow_dispatch:
    inputs:
      commit:
        type: boolean
        default: true
        required: true
        description: Commit new Goldens to this branch.

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3

      - name: 🏗 Build and test Sweyer
        uses: ./.github/workflows/build_and_test
        with:
          testing_arguments: --update-goldens

      - name: 📁 Save updated Golden test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: golden-test-updated
          path: test/golden/goldens

      - name: 💂 Verify that ${{ github.actor }} has permission to commit
        if: github.event.inputs.commit == 'true'
        id: permissionCheck
        uses: actions-cool/check-user-permission@v2
        with:
          require: write
      - name: 💾 Commit updated Golden test artifacts
        uses: stefanzweifel/git-auto-commit-action@v4
        if: github.event.inputs.commit == 'true' && steps.permissionCheck.outputs.require-result == 'true'
        with:
          commit_message: 🤖 Update Golden test artifacts 🤖
